name: Wisersell - Automation -Tests

# on:
  # push:
    # branches: [main]
    # # pull_request:
    # #   branches: [ main ]
  # workflow_dispatch:
  # schedule:
    # - cron: '30 3 * * *'
jobs:
    test:
      
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up JDK 19
        id: Set-up-JDK-19
        uses: actions/setup-java@v1
        with:
          java-version: '19'
          # distribution: 'temurin'
          # cache: maven
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Test with Maven
        id: Test-with-Maven
        if: always()
        run: mvn -B package --file pom.xml
      - name: upload-test-results
        id: upload-test-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Report
          path: target
          retention-days: 2

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        if: always()
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'target'
      - name: Link to report
        id: Link-to-report
        if: always()
        run: echo "https://dev2.wisersell.com.s3.us-east-1.amazonaws.com/${{steps.S3.outputs.object_key}}/html-reports/Run_Smoke_Test.html"

      - name: Slack notification
        id: Slack-notification
        uses: act10ns/slack@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: 'version-2-notification'
          config: .github/config/slack-main.yaml
          message: Testing {{ env.GITHUB_REF_NAME }} branch for VERSION-2 AUTOMATION TESTS
                    "https://dev2.wisersell.com.s3.us-east-1.amazonaws.com/${{steps.S3.outputs.object_key}}/html-reports/Run_Smoke_Test.html"
        if: always()
    
